source: arm.yaml
port: /dev/ttyUSB0
read_rate:  50
write_rate: 50
joints: {
    joint1: {id: 1, neutral: 205, max_angle: 269.6, min_angle: -269.6, max_speed: 90},
    joint2: {id: 2, max_angle: 180, min_angle: -180.0, max_speed: 90},
    joint3: {id: 3, max_angle: 180, min_angle: -180.0, max_speed: 90},
    joint4: {id: 4, max_angle: 180, min_angle: -180.0, max_speed: 90},
    joint5: {id: 5, max_angle: 180, min_angle: -180.0, max_speed: 90},
    joint6: {id: 6, max_angle: 180, min_angle: -180.0, max_speed: 90},
    joint7_2: {id: 7,max_angle: 180, min_angle: -180.0, max_speed: 90},
}

controllers: {
    arm_controller: {type: follow_controller, joints: [joint1, joint2, joint3,joint4, joint5, joint6], action_name: arm_controller/follow_joint_trajectory, onboard: False },
    hand_controller: {type: follow_controller, joints: [joint7_2], action_name: hand_controller/follow_joint_trajectory, onboard: False }
}